' This is a comment!
@startuml

title "Test Sequence Diagram"

actor Alice
box #lightBlue
	actor Bob
	database DB
end box

Alice->Bob: Hello!
Bob->DB: Check localization
DB-->Bob: Spanish
Bob-->Alice: Hola!!

@enduml
